version: '3'
services:
  api:
    container_name: api
    build: ./
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: npm start
    ports:
      - '8090:8090'
    volumes:
      - ./api:/web
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
